# Project: doubly linked lists
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o rezero.o
LINKOBJ  = main.o rezero.o
LIBS     = -L"G:/DevCpp/Dev-Cpp/TDM-GCC-64/lib" -L"G:/DevCpp/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"G:/DevCpp/Dev-Cpp/TDM-GCC-64/include" -I"G:/DevCpp/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"G:/DevCpp/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"G:/DevCpp/Dev-Cpp/TDM-GCC-64/include" -I"G:/DevCpp/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"G:/DevCpp/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"G:/DevCpp/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = "doubly linked lists.exe"
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
DEL      = G:\DevCpp\Dev-Cpp\devcpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

rezero.o: rezero.cpp
	$(CPP) -c rezero.cpp -o rezero.o $(CXXFLAGS)
